language: python
python:
  - 3.4
  - 2.7
script: python3 fruta.py


matrix:
  include:
    - name: "Version Tests"
      python: 3.8
      env: TEST_SUITE=suite_3_5_unit
    - name: "PHP Configurations"
      before_script: 
      - sudo apt update
      - sudo apt-cache pkgnames | grep php7.0
      - sudo apt install -y php7.0 php7.0-cli php7.0-common php7.0-mbstring php7.0-intl php7.0-xml php7.0-mysql php7.0-mcrypt
      - sudo php -v
      - sudo curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
      script: php7.0 Hello_World.php
      env: TEST_SUITE=suite_7_0_unit
